# Generated by Django 5.2.3 on 2025-07-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
