# Generated by Django 5.2.3 on 2025-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
