# Generated by Django 5.2.3 on 2025-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_order_amount_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_payed',
        ),
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.CharField(default=False),
        ),
    ]
